version: '3.8'
services:
  iptv-proxy:
    image: sure155/iptvs-app:latest
    container_name: iptv-proxy
    restart: unless-stopped
    ports:
      - "${PROXY_PORT:-8830}:8830"
    env_file:
      - .env
    networks:
      - iptv_net

networks:
  iptv_net:
    driver: bridge
